/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-06-30 05:55:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');


	HttpSession session = request.getSession(false);
	if(session == null) {
		response.sendRedirect("login.jsp");
			return;
	}

	String useridx = (String)session.getAttribute("login.useridx");
	String id = (String)session.getAttribute("login.id");
	String pwd = (String)session.getAttribute("login.pwd");
	String username = (String)session.getAttribute("login.username");
	String useraddress = (String)session.getAttribute("login.useraddress");


      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>EReceipt</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"main_contents.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write(" <body>\r\n");
      out.write(" \r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<h1><img src=\"./images/logo.gif\" alt=\"전자영수증 관리체계\" ></h1>\r\n");
      out.write("\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t<span class=\"inp_search\"><input type=\"text\" title=\"검색어 입력\" name=\"input1\"></span>\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn_search\"><span class=\"txt_hid\">검색</span></button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<nav class=\"gnb\">\r\n");
      out.write("\t\t\t<ul class=\"sub_menu1\">\r\n");
      out.write("\t\t\t\t<li><a href=\"product_save.jsp\">상품등록</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"product_purchase.jsp\">구매내용</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"contents\">\r\n");
      out.write("\t\t <div class=\"subcontents1\">\r\n");
      out.write("\t\t\t<section>\r\n");
      out.write("\t\t\t\t<div class=\"banner\">\r\n");
      out.write("\t\t\t\t\t<img src=\"http://placehold.it/635x100\" alt=\"배너\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"news1\">\r\n");
      out.write("\t\t\t\t\t<h3>연합뉴스 <span></span></h3>\r\n");
      out.write("\t\t\t\t\t<div>'50만원 바가지'…견인차 횡포 극성</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"news2\">\r\n");
      out.write("\t\t\t\t\t\t<li>네이버 뉴스</li>\r\n");
      out.write("\t\t\t\t\t\t<li><span>|</span> 연예</li>\r\n");
      out.write("\t\t\t\t\t\t<li><span>|</span>스포스</li>\r\n");
      out.write("\t\t\t\t\t\t<li><span>|</span>경제</li>\r\n");
      out.write("\t\t\t\t\t\t<li><span>|</span>오늘의 신문</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"newslist\">\r\n");
      out.write("\t\t\t\t\t<div class=\"news_tit\">\r\n");
      out.write("\t\t\t\t\t\t<h2>뉴스 스탠드 <span></span></h2>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<strong>전체 언론사</strong> <span>|</span> MY뉴스\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"newsCont\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"http://placehold.it/81x73\" alt=\"언론사 목록\"></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"news_ft\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ico\">구독설정</span> <span class=\"col_gr\">|</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span>[알림]언론사별 주요뉴스를 메인에서 바로 볼 수 있어요!</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<aside>\r\n");
      out.write("\t\t\t\t<div class=\"login\">\r\n");
      out.write("\t\t\t\t\t<p class=\"join_link\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" title=\"회원가입 페이지로 이동\">회원정보수정</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"login_box\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"id\" class=\"login_label\">아이디</label>\r\n");
      out.write("\t\t\t\t\t\t\t아이디: ");
      out.print(id );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"login_box\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"login_pwd\" class=\"login_label\">비밀번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t비밀번호: ");
      out.print(pwd );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"login_box\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"login_pwd\" class=\"login_label\">매장명</label>\r\n");
      out.write("\t\t\t\t\t\t\t매장명: ");
      out.print(username );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"login_box\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"login_pwd\" class=\"login_label\">주소</label>\r\n");
      out.write("\t\t\t\t\t\t\t주소: ");
      out.print(useraddress );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<form name=\"login_form\" action=\"login.jsp\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"image\" src=\"http://14.63.212.205/html/18_ksaedu/01_user/images/total/btn/btn_logout2.gif\" \r\n");
      out.write("\t\t\t\t\t\ttitle=\"로그아웃\" alt=\"로그아웃\" class=\"login_btn\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"security\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"security_txt\">IP보안 <span class=\"security_on\">ON</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dis_login_box\"><a herf=\"#\" class=\"dis_login\"><span>일회용 로그인</span></a></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"today_box\">\r\n");
      out.write("\t\t\t\t\t<h3>투데이 <span></span></h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"today_link\">\r\n");
      out.write("\t\t\t\t\t\t<strong>10.13.</strong>(월)<span>|</span> TV편성\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"today_cont\">\r\n");
      out.write("\t\t\t\t\t\t<li><strong>신문1면</strong><span></span>\"5.24제재, 남북 만나 대화로 풀어야\"</li>\r\n");
      out.write("\t\t\t\t\t\t<li><strong>학습</strong><span></span>영어로 듣는 뉴스 | 오늘의 글로벌 회화</li>\r\n");
      out.write("\t\t\t\t\t\t<li><strong>스포츠</strong><span></span>'4홈런' 세인트루이스, NLCS 2차전 승리</li>\r\n");
      out.write("\t\t\t\t\t\t<li><strong>증시</strong><span></span>코스닥 534.31</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ad\">\r\n");
      out.write("\t\t\t\t\t<img src=\"http://placehold.it/298x150\" alt=\"광고배너\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</aside>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\r\n");
      out.write("\t\t <div class=\"subcontents2\"></div>\r\n");
      out.write("\t\t <div class=\"subcontents3\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer></footer>\r\n");
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
