/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-06-30 05:55:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.PreparedStatement;
import java.sql.*;

public final class product_005fmodify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");


String productidx = request.getParameter("productidx");

request.setCharacterEncoding("utf-8");

try {
	
	
	Class.forName("com.mysql.jdbc.Driver");  
	String DB_URL ="jdbc:mysql://localhost:3306/ereceiptdb?useSSL=false";

	Connection con =  DriverManager.getConnection(DB_URL, "admin", "1234");
	
	String sql = "SELECT *FROM product_list WHERE productidx=?";
	
	PreparedStatement pstmt = con.prepareStatement(sql);
	
	pstmt.setString(1, productidx);

	ResultSet rs = pstmt.executeQuery();
	
	if(rs.next()) {
	

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>EReceipt</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("  html, body {\r\n");
      out.write("  font-family: Arial, sans-serif;\r\n");
      out.write("  background: #fff;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  min-width: 100%;\r\n");
      out.write("  font-size: 13px;\r\n");
      out.write("  color: #404040;\r\n");
      out.write("  direction: ltr;\r\n");
      out.write("  -webkit-text-size-adjust: none;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("\r\n");
      out.write("\ttop:  50px;\r\n");
      out.write("\tleft: 20%;\r\n");
      out.write("\twidth: 60%;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tbackground-color: gray;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form {\r\n");
      out.write("\ttop: 60px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function chk_blank() {\r\n");
      out.write("\t\r\n");
      out.write("\t   if(document.modify_form.productname.value==\"\") {\r\n");
      out.write("\t\t\talert(\"상품명을 입력하세요\");\t\r\n");
      out.write("\t\t\treturn false;\t\t\r\n");
      out.write("\t\t} \r\n");
      out.write("\t   \r\n");
      out.write("\t   if(document.modify_form.productprice.value==\"\") {\r\n");
      out.write("\t\t\talert(\"가격을 입력하세요\");\t\r\n");
      out.write("\t\t\treturn false;\t\r\n");
      out.write("\t\t} \r\n");
      out.write("\t   if(document.modify_form.productcategory.value==\"\") {\r\n");
      out.write("\t\t\talert(\"분류를 입력하세요\");\t\r\n");
      out.write("\t\t\treturn false;\t\r\n");
      out.write("\t\t} \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"content\" align=\"center\">\r\n");
      out.write("<h2>전자영수증 관리체계</h2>\r\n");
      out.write("\r\n");
      out.write("<form name=\"modify_form\" method=\"post\" action=\"product_modify_do.jsp?productidx=");
      out.print(productidx );
      out.write("\">\r\n");
      out.write("<div class=\"form\">\r\n");
      out.write("<p>상품명</p><input type=\"text\" name=\"productname\" value=\"");
      out.print(rs.getString("productname") );
      out.write("\" size=\"12\"><br>\r\n");
      out.write("<p>가격</p><input type=\"number\" name=\"productprice\" value=\"");
      out.print(rs.getString("productprice") );
      out.write("\" min=\"0\" step=\"1\"><br>\r\n");
      out.write("<p>분류</p><input type=\"text\" name=\"productcategory\" value=\"");
      out.print(rs.getString("productcategory") );
      out.write("\" size=\"12\"><br>\r\n");
      out.write("<br>\r\n");
      out.write("<input type=\"submit\" value=\"수정\" onclick=\"return chk_blank()\">\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");

	}
rs.close();	
pstmt.close();
con.close();

}catch(SQLException e) {
out.print(e);
return;
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
